### ISSUE TITLE
"square" and emojis

### ISSUE THREAD

**Issue by cemulate** [HDembinski/unicodeitplus#3]
(Apologies in advance for the _very_ nitpicky issue, love what you've done with unicodeitplus!)

According to [src/unicodeitplus/data.py#178](https://github.com/HDembinski/unicodeitplus/blob/main/src/unicodeitplus/data.py#L178) and `unimathsymbols.txt`, `\square` is defined as ⬜ `0x2B1C` which, [according to Wikipedia](https://en.wikipedia.org/wiki/Miscellaneous_Symbols_and_Arrows#Emoji), is an "emoji". Indeed it renders rather "emoji-like" in many fonts, creating jarring contrast with nearby characters.

It seems to me that `\square` should probably be □ `0x25A1` "white square", as this seems like the most faithful interpretation of `\square`, even though this is already available as the (quite verbose) `\mdlgwhtsquare`

I created an issue instead of a PR because it may be worth some discussion on whether or not "emojis" should be avoided whenever possible (when the character has a non-emoji interpretation). I presume "is an emoji" may be some defined predicate on characters and hence searchable in the data file.

**Comment by HDembinski** [comment]
Cool, thanks for the issue. I am relying on unimathsymbols.txt for the conversion, but we can of course override it to "fix" it. I don't know how to do this automatically, so would do it case-by-case when someone like you reports something.
